#!/bin/bash

platform="$1"
agent="$2"
outdir="$HOME/offsec/dav"


cd "$(dirname "$(realpath "${BASH_SOURCE[0]}")")" || exit
set -e

cp "../agents/$agent.nim" .
sd 'AGENT' "$agent" Dockerfile
docker build -t ron-builder .

cmd="cd /root && nim c -d:release --mm:orc --passL:\"-static -lsodium\" $agent.nim && mv $agent /out && chmod +w /out/$agent && chown user /out/$agent"

if [[ "$platform" == 'lin' ]]; then
  docker run --rm \
    -v "$PWD/bin":/out \
    ron-builder \
    sh -c "$cmd"
#  chmod +w "bin/$agent"
  strip --strip-all "bin/$agent"
  mv "bin/$agent" "$outdir"
elif [[ "$platform" == 'win' ]]; then
  nim c -d:release --cpu:amd64 --os:windows \
    --gcc.exe:x86_64-w64-mingw32-gcc \
    --gcc.linkerexe:x86_64-w64-mingw32-gcc \
    --passL:"-static -static-libgcc -static-libstdc++" \
    "$agent".nim
#  chmod +w "bin/$agent.exe"
  strip --strip-all "bin/$agent.exe"
  mv "bin/$agent.exe" "$outdir"
fi

rm "$agent.nim"
until rg -q 'AGENT' Dockerfile; do
  sd "$agent" 'AGENT' Dockerfile
done
